import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  CheckCircle2,
  Circle,
  Trash2,
  Share2,
  Plus,
  Minus,
  Search,
  CheckCheck,
  RefreshCw,
  Copy,
  FileSpreadsheet,
  Download,
  Pencil,
  Check,
  X,
} from "lucide-react";
import { CartItem, CURRENCIES, CurrencyConfig } from "../types";
import { sounds } from "../utils/soundEffects";
import { exportCartToCSV } from "../utils/csvExport";
import confetti from "canvas-confetti";

interface CartListProps {
  items: CartItem[];
  currency: string;
  budgetLimit?: number;
  onToggleCheck: (id: string) => void;
  onUpdateQuantity: (id: string, delta: number) => void;
  onDeleteItem: (id: string) => void;
  onClearChecked: () => void;
  onClearAll: () => void;
  onCheckAll: () => void;
  onDuplicateItem: (item: CartItem) => void;
  onEditItem?: (id: string, updated: { name?: string; price?: number; quantity?: number }) => void;
}

export const CartList: React.FC<CartListProps> = ({
  items,
  currency,
  budgetLimit = 0,
  onToggleCheck,
  onUpdateQuantity,
  onDeleteItem,
  onClearChecked,
  onClearAll,
  onCheckAll,
  onDuplicateItem,
  onEditItem,
}) => {
  const [searchQuery, setSearchQuery] = useState("");
  const [sortBy, setSortBy] = useState<"added" | "price-desc" | "price-asc" | "name">("added");

  // Inline item editing state
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editName, setEditName] = useState("");
  const [editPrice, setEditPrice] = useState("");

  const startEditing = (item: CartItem) => {
    setEditingId(item.id);
    setEditName(item.name);
    setEditPrice(item.price.toString());
    sounds.playClick();
  };

  const cancelEditing = () => {
    setEditingId(null);
    setEditName("");
    setEditPrice("");
    sounds.playClick();
  };

  const saveEditing = (id: string) => {
    if (!editName.trim()) return;
    const numPrice = Math.max(0, parseFloat(editPrice) || 0);
    if (onEditItem) {
      onEditItem(id, { name: editName.trim(), price: numPrice });
    }
    setEditingId(null);
    sounds.playAdd();
  };

  const currentCurr: CurrencyConfig = CURRENCIES[currency] || CURRENCIES.PKR;

  // Filter items
  const filteredItems = items
    .filter((item) => item.name.toLowerCase().includes(searchQuery.toLowerCase()))
    .sort((a, b) => {
      if (sortBy === "price-desc") return b.price * b.quantity - a.price * a.quantity;
      if (sortBy === "price-asc") return a.price * a.quantity - b.price * b.quantity;
      if (sortBy === "name") return a.name.localeCompare(b.name);
      return b.addedAt - a.addedAt;
    });

  const checkedCount = items.filter((i) => i.checked).length;
  const totalCost = items.reduce((sum, i) => sum + i.price * i.quantity, 0);

  // WhatsApp Share Formatter
  const handleShareWhatsApp = () => {
    sounds.playClick();

    let text = `🛒 *Smart Cart AI Shopping List*\n`;
    text += `--------------------------------\n`;

    items.forEach((item, index) => {
      const status = item.checked ? "✅" : "⏳";
      const itemTotal = item.price * item.quantity;
      text += `${status} ${index + 1}. *${item.name}* x${item.quantity} - ${currentCurr.symbol} ${itemTotal.toLocaleString()}\n`;
    });

    text += `--------------------------------\n`;
    text += `📊 *Total Items:* ${items.length}\n`;
    text += `💰 *Grand Total:* ${currentCurr.symbol} ${totalCost.toLocaleString()}\n`;
    text += `✨ *Generated by Smart Cart AI*`;

    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, "_blank");

    confetti({
      particleCount: 30,
      spread: 50,
      origin: { y: 0.8 },
    });
  };

  return (
    <div className="w-full max-w-6xl mx-auto px-3 sm:px-4 mt-4 pb-28">
      {/* Search & Sort Bar */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2.5 mb-4">
        {/* Search bar */}
        <div className="relative flex-1">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search household items or bills..."
            className="w-full bg-white/5 border border-white/10 focus:border-fuchsia-500/50 text-white placeholder-slate-400 text-xs font-semibold rounded-xl sm:rounded-2xl pl-10 pr-4 py-2.5 sm:py-3 outline-none focus:ring-2 focus:ring-fuchsia-500/30 transition-all backdrop-blur-md"
          />
        </div>

        {/* Sort Selector */}
        <select
          value={sortBy}
          onChange={(e) => setSortBy(e.target.value as any)}
          className="bg-white/5 hover:bg-white/10 text-slate-200 text-xs font-bold border border-white/10 rounded-xl sm:rounded-2xl px-3 py-2.5 sm:py-3 outline-none cursor-pointer transition-all backdrop-blur-md"
        >
          <option value="added" className="bg-slate-950 text-white">Newest First</option>
          <option value="price-desc" className="bg-slate-950 text-white">Price: High to Low</option>
          <option value="price-asc" className="bg-slate-950 text-white">Price: Low to High</option>
          <option value="name" className="bg-slate-950 text-white">Name A-Z</option>
        </select>
      </div>

      {/* Cart Quick Action Toolbar */}
      <div className="flex items-center justify-between bg-black/40 backdrop-blur-xl px-3.5 py-2.5 rounded-xl sm:rounded-2xl border border-white/10 mb-4 text-xs shadow-lg">
        <div className="text-slate-300 font-semibold flex items-center gap-2">
          <span>
            {checkedCount}/{items.length} Checked
          </span>
          {checkedCount === items.length && items.length > 0 && (
            <span className="text-[10px] font-extrabold text-emerald-300 bg-emerald-500/20 px-2 py-0.5 rounded-full border border-emerald-500/30">
              🎉 Completed!
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => exportCartToCSV(items, budgetLimit, currency)}
            title="Export cart items & budget summary to CSV spreadsheet file"
            className="text-[11px] font-bold text-emerald-300 hover:text-emerald-200 bg-emerald-500/20 hover:bg-emerald-500/30 px-2.5 py-1.5 rounded-xl border border-emerald-500/40 transition-all cursor-pointer flex items-center gap-1.5"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-400" />
            <span className="hidden xs:inline">Export CSV</span>
          </button>

          <button
            onClick={onCheckAll}
            title="Toggle check all items"
            className="text-[11px] font-bold text-slate-300 hover:text-fuchsia-300 bg-white/5 hover:bg-white/10 px-2.5 py-1.5 rounded-xl border border-white/10 transition-all cursor-pointer flex items-center gap-1.5"
          >
            <CheckCheck className="w-3.5 h-3.5 text-fuchsia-400" />
            <span className="hidden xs:inline">Check All</span>
          </button>

          {checkedCount > 0 && (
            <button
              onClick={onClearChecked}
              className="text-[11px] font-bold text-rose-300 hover:text-rose-200 bg-rose-500/20 hover:bg-rose-500/30 px-2.5 py-1.5 rounded-xl border border-rose-500/40 transition-all cursor-pointer flex items-center gap-1.5"
            >
              <Trash2 className="w-3.5 h-3.5" />
              <span className="hidden xs:inline">Clear Done</span>
            </button>
          )}

          <button
            onClick={onClearAll}
            className="text-[11px] font-bold text-slate-400 hover:text-rose-400 p-1.5 rounded-xl hover:bg-white/5 transition-all cursor-pointer"
            title="Clear entire cart"
          >
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Cart Item Cards List (Responsive for PC/Desktop & Mobile) */}
      {filteredItems.length === 0 ? (
        <div className="flex flex-col items-center justify-center p-8 sm:p-12 bg-white/5 backdrop-blur-md rounded-2xl sm:rounded-3xl border border-white/10 text-center gap-3">
          <motion.div
            animate={{ y: [0, -8, 0], rotate: [0, 5, -5, 0] }}
            transition={{ repeat: Infinity, duration: 4, ease: "easeInOut" }}
            className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-indigo-500/20 to-fuchsia-500/20 border border-white/10 flex items-center justify-center text-fuchsia-300 text-3xl shadow-xl"
          >
            🛒
          </motion.div>
          <div>
            <h3 className="text-sm sm:text-base font-extrabold text-slate-100">Your household list is empty</h3>
            <p className="text-xs text-slate-400 mt-1 max-w-sm mx-auto">
              Add daily items (Milk, Eggs, Electricity Bill) using the form above, voice mic 🎙️, or barcode scanner 📷!
            </p>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          <AnimatePresence>
            {filteredItems.map((item) => {
              const itemTotal = item.price * item.quantity;
              
              // Helper to pick 3D animated emoji badge based on item name
              const getItemEmoji = (itemName: string) => {
                const lower = itemName.toLowerCase();
                if (lower.includes("milk")) return "🥛";
                if (lower.includes("egg")) return "🥚";
                if (lower.includes("bread")) return "🍞";
                if (lower.includes("rice")) return "🍚";
                if (lower.includes("flour") || lower.includes("atta")) return "🌾";
                if (lower.includes("tea") || lower.includes("coffee")) return "🍵";
                if (lower.includes("bill") || lower.includes("electri") || lower.includes("power")) return "⚡";
                if (lower.includes("gas") || lower.includes("sui")) return "🔥";
                if (lower.includes("net") || lower.includes("wifi") || lower.includes("fiber")) return "📶";
                if (lower.includes("water")) return "💧";
                if (lower.includes("rent")) return "🏠";
                if (lower.includes("oil") || lower.includes("ghee")) return "🌻";
                if (lower.includes("soap") || lower.includes("surf") || lower.includes("clean")) return "🧼";
                if (lower.includes("chicken") || lower.includes("meat")) return "🍗";
                if (lower.includes("apple") || lower.includes("fruit")) return "🍎";
                if (lower.includes("banana")) return "🍌";
                return "🛍️";
              };

              const emoji = getItemEmoji(item.name);
              const isEditing = editingId === item.id;

              return (
                <motion.div
                  key={item.id}
                  layout
                  initial={{ opacity: 0, y: 12, scale: 0.98 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95, height: 0 }}
                  transition={{ duration: 0.2 }}
                  className={`group relative flex flex-col sm:flex-row sm:items-center justify-between p-3.5 sm:p-4 rounded-xl sm:rounded-2xl border transition-all duration-200 backdrop-blur-md gap-3 ${
                    isEditing
                      ? "bg-fuchsia-950/40 border-fuchsia-500/60 ring-2 ring-fuchsia-500/30 shadow-2xl"
                      : item.checked
                      ? "bg-black/40 border-white/5 opacity-50"
                      : "bg-gradient-to-r from-white/10 via-white/5 to-transparent border-white/10 hover:border-fuchsia-500/30 shadow-xl"
                  }`}
                >
                  {isEditing ? (
                    /* Inline Editing Mode UI Form Row */
                    <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 w-full">
                      <div className="flex items-center gap-2 flex-1 min-w-0">
                        <span className="text-xl p-1">{emoji}</span>
                        <input
                          type="text"
                          value={editName}
                          onChange={(e) => setEditName(e.target.value)}
                          placeholder="Item name..."
                          autoFocus
                          className="flex-1 bg-black/60 border border-fuchsia-500/50 text-white text-xs sm:text-sm font-bold rounded-xl px-3 py-1.5 outline-none focus:ring-2 focus:ring-fuchsia-400"
                        />
                      </div>

                      <div className="flex items-center gap-2">
                        <div className="relative w-28 sm:w-32">
                          <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-xs font-bold text-fuchsia-400">
                            {currentCurr.symbol}
                          </span>
                          <input
                            type="number"
                            min="0"
                            step="any"
                            value={editPrice}
                            onChange={(e) => setEditPrice(e.target.value)}
                            placeholder="Price"
                            className="w-full bg-black/60 border border-fuchsia-500/50 text-white text-xs font-bold rounded-xl pl-8 pr-2 py-1.5 outline-none focus:ring-2 focus:ring-fuchsia-400"
                          />
                        </div>

                        <div className="flex items-center gap-1.5 ml-auto">
                          <button
                            onClick={() => saveEditing(item.id)}
                            title="Save Changes"
                            className="p-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 rounded-xl font-bold transition-all cursor-pointer flex items-center gap-1 shadow-lg"
                          >
                            <Check className="w-4 h-4" />
                            <span className="text-xs font-black">Save</span>
                          </button>
                          <button
                            onClick={cancelEditing}
                            title="Cancel Edit"
                            className="p-2 bg-white/10 hover:bg-white/20 text-slate-300 rounded-xl transition-all cursor-pointer"
                          >
                            <X className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    </div>
                  ) : (
                    /* Standard Row View */
                    <>
                      {/* Left: Checkbox + Animated 3D Icon + Item Name */}
                      <div className="flex items-center gap-3 flex-1 min-w-0">
                        <button
                          onClick={() => {
                            onToggleCheck(item.id);
                            if (!item.checked) sounds.playCheck();
                          }}
                          className="cursor-pointer text-fuchsia-400 hover:scale-110 transition-transform p-0.5 shrink-0"
                        >
                          {item.checked ? (
                            <CheckCircle2 className="w-5 h-5 text-emerald-400 fill-emerald-400/20" />
                          ) : (
                            <Circle className="w-5 h-5 text-slate-500 hover:text-fuchsia-400" />
                          )}
                        </button>

                        {/* Animated Item Icon Avatar */}
                        <motion.div
                          whileHover={{ scale: 1.15, rotate: 10 }}
                          className="w-9 h-9 rounded-xl bg-white/10 border border-white/10 flex items-center justify-center text-lg shrink-0 shadow-inner"
                        >
                          {emoji}
                        </motion.div>

                        <div className="flex flex-col min-w-0 flex-1">
                          <span
                            className={`text-xs sm:text-sm font-bold truncate ${
                              item.checked ? "line-through text-slate-500" : "text-slate-100"
                            }`}
                          >
                            {item.name}
                          </span>

                          <div className="flex items-center gap-2 text-[11px] font-semibold text-slate-400 mt-0.5">
                            <span className="text-fuchsia-300 font-bold">
                              {currentCurr.symbol} {item.price.toLocaleString()} each
                            </span>
                            {item.barcode && (
                              <span className="text-[10px] bg-white/10 text-slate-300 px-1.5 py-0.5 rounded font-mono border border-white/10 hidden xs:inline">
                                {item.barcode}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>

                      {/* Right: Stepper & Price & Actions */}
                      <div className="flex items-center justify-between sm:justify-end gap-3 shrink-0 pt-2 sm:pt-0 border-t sm:border-t-0 border-white/5">
                        {/* Quantity Stepper */}
                        <div className="flex items-center bg-black/60 border border-white/15 rounded-xl p-1">
                          <button
                            onClick={() => {
                              onUpdateQuantity(item.id, -1);
                              sounds.playClick();
                            }}
                            className="w-6 h-6 rounded-lg bg-white/10 hover:bg-white/20 text-slate-200 flex items-center justify-center transition-colors cursor-pointer text-xs font-bold"
                          >
                            <Minus className="w-3 h-3" />
                          </button>
                          <span className="w-8 text-center text-xs font-black text-white">
                            {item.quantity}
                          </span>
                          <button
                            onClick={() => {
                              onUpdateQuantity(item.id, 1);
                              sounds.playClick();
                            }}
                            className="w-6 h-6 rounded-lg bg-white/10 hover:bg-white/20 text-slate-200 flex items-center justify-center transition-colors cursor-pointer text-xs font-bold"
                          >
                            <Plus className="w-3 h-3" />
                          </button>
                        </div>

                        {/* Total item price */}
                        <div className="text-right min-w-[80px]">
                          <span className="text-xs sm:text-sm font-black text-fuchsia-300 block">
                            {currentCurr.symbol} {itemTotal.toLocaleString()}
                          </span>
                        </div>

                        {/* Actions Menu */}
                        <div className="flex items-center gap-1 border-l border-white/10 pl-2">
                          <button
                            onClick={() => startEditing(item)}
                            title="Edit Item (Name & Price)"
                            className="p-1.5 text-slate-400 hover:text-amber-300 hover:bg-amber-500/20 rounded-lg transition-all cursor-pointer"
                          >
                            <Pencil className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => {
                              onDuplicateItem(item);
                              sounds.playAdd();
                            }}
                            title="Duplicate item"
                            className="p-1.5 text-slate-400 hover:text-fuchsia-300 hover:bg-white/10 rounded-lg transition-all cursor-pointer"
                          >
                            <Copy className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => {
                              onDeleteItem(item.id);
                              sounds.playClick();
                            }}
                            title="Delete item"
                            className="p-1.5 text-slate-400 hover:text-rose-400 hover:bg-rose-500/20 rounded-lg transition-all cursor-pointer"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    </>
                  )}
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      )}

      {/* Floating Sticky Actions Bar (Export CSV & Share WhatsApp) */}
      <div className="fixed bottom-4 left-0 right-0 max-w-xl mx-auto px-3 z-30">
        <div className="flex items-center gap-2">
          <button
            onClick={() => exportCartToCSV(items, budgetLimit, currency)}
            title="Download CSV spreadsheet report"
            className="flex-1 bg-gradient-to-r from-emerald-700 via-teal-700 to-emerald-600 hover:brightness-110 text-white font-extrabold uppercase tracking-wider text-[11px] sm:text-xs py-3 px-3.5 rounded-2xl shadow-2xl shadow-emerald-600/30 border border-emerald-400/30 flex items-center justify-center gap-2 transition-all active:scale-98 cursor-pointer backdrop-blur-xl"
          >
            <Download className="w-4 h-4 text-emerald-300 shrink-0" />
            <span className="truncate">📥 Export CSV</span>
          </button>

          <button
            onClick={handleShareWhatsApp}
            className="flex-[1.4] bg-gradient-to-r from-teal-600 via-emerald-600 to-teal-500 hover:brightness-110 text-white font-extrabold uppercase tracking-wider text-[11px] sm:text-xs py-3 px-3.5 rounded-2xl shadow-2xl shadow-teal-500/30 border border-white/20 flex items-center justify-center gap-2 transition-all active:scale-98 cursor-pointer backdrop-blur-xl"
          >
            <Share2 className="w-4 h-4 shrink-0" />
            <span className="truncate">📲 Share WhatsApp ({items.length})</span>
          </button>
        </div>
      </div>
    </div>
  );
};

